version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
    timezone: Australia/Sydney
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
