name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1

      - name: rustfmt
        run: .ci-scripts/rustfmt-check

      - name: build
        run: cargo build --verbose

      - name: test
        run: cargo test --verbose
